const passages = [
  "the morning market slowly became crowded as vendors arranged fresh fruits vegetables flowers and snacks across long rows of small stalls while customers moved carefully through the narrow paths comparing prices greeting familiar faces and carrying bags filled with items for the rest of the week as the sound of traffic conversations and distant music blended together in the background creating the feeling of another busy day beginning in the center of the city where people from different neighborhoods gathered before work school and other responsibilities",

  "a young developer spent several months building an online typing competition platform where players could join public rooms race against friends track their typing speed and improve accuracy through daily practice sessions while also learning how realtime communication authentication databases and responsive interfaces work together in modern web applications because each new feature introduced unexpected bugs design problems and performance challenges that required patience testing and continuous learning before the project finally became stable enough for regular users",

  "during the journey across the countryside the passengers looked through the train windows at long green fields rivers small villages and distant mountains while children shared snacks families discussed travel plans and students listened to music while preparing for upcoming exams because the slow movement of the train combined with the cool evening air created a peaceful atmosphere that felt very different from the crowded streets noisy traffic and constant pressure of life in large cities where people rarely have enough time to slow down and relax",

  "many students begin learning programming with excitement but quickly become frustrated when they encounter confusing errors incomplete documentation and projects that fail without obvious reasons however consistent practice reading code written by others and building small applications step by step can gradually improve problem solving skills logical thinking and confidence because most experienced developers also spent years making mistakes debugging strange issues and learning new technologies through experimentation persistence and curiosity rather than natural talent alone",

  "the football match attracted thousands of supporters who filled the stadium with songs cheers and colorful banners while players warmed up on the field coaches discussed tactics and photographers moved quickly near the sidelines preparing to capture important moments because everyone understood that a single mistake clever pass or unexpected goal could completely change the result of the game and create memories that fans would continue discussing for many years after the final whistle had already been blown",

  "late at night the small apartment remained illuminated by the light of computer screens as designers programmers and editors worked together remotely to complete an important project before the deadline while exchanging ideas through video calls reviewing documents correcting mistakes and organizing tasks across multiple devices because modern teamwork often depends on reliable internet communication clear planning and the ability to coordinate people living in different cities countries and time zones without ever meeting in person",

  "after several days of heavy rainfall the rivers began overflowing into nearby roads parks and residential areas causing transportation delays power outages and temporary closures across multiple neighborhoods while emergency teams distributed supplies guided families to safer locations and monitored changing weather conditions because strong storms can quickly affect communication systems public services and daily routines especially in regions where large populations live close to lakes rivers or coastal areas during seasonal weather changes",

  "the university library became especially crowded before final examinations as students searched for textbooks revised important concepts solved practice problems and discussed assignments with classmates while others quietly typed notes highlighted reference materials and prepared presentations for upcoming evaluations because academic success often depends not only on intelligence but also on time management discipline healthy routines and the willingness to remain focused even during long stressful weeks filled with deadlines and difficult subjects",

  "a small startup company introduced a new productivity application designed to help teams organize schedules manage collaborative projects share updates and monitor progress from different devices while engineers collected user feedback improved security optimized server performance and added requested features because software products rarely become successful immediately and usually require constant improvement adaptation and support before gaining the trust of businesses students and independent professionals who depend on them for everyday work",

  "early in the morning runners cyclists and walkers filled the public park while street cleaners prepared pathways gardeners watered plants and food vendors arranged carts selling tea fruit sandwiches and snacks because outdoor spaces often provide people with opportunities to exercise relax socialize and temporarily escape from the stress of busy workplaces crowded transportation systems and endless notifications from phones computers and social media platforms that compete constantly for attention throughout the day",
];
function getRandomPassage() {
  return passages[Math.floor(Math.random() * passages.length)];
}

module.exports = { getRandomPassage };
